mail/delete-old-userdata: Print errors to stderr
Before, they were only written to the syslog.

diff --git a/ansible/roles/mail/delete-old-userdata/templates/delete-old-userdata.bash.j2 b/ansible/roles/mail/delete-old-userdata/templates/delete-old-userdata.bash.j2
--- a/ansible/roles/mail/delete-old-userdata/templates/delete-old-userdata.bash.j2
+++ b/ansible/roles/mail/delete-old-userdata/templates/delete-old-userdata.bash.j2
@@ -125,6 +125,16 @@ function log()
 }
 
 
+function error()
+{
+  [[ $# -eq 1 ]]
+  local -r message="$1"
+  log error "$message"
+  printf '%s\n' "$message" >&2
+  return 1
+}
+
+
 function get_dirs_from_db()
 {
   tmpfiles[dirs-db-unsorted]="$(umask 077; mktemp -t tmp.XXXXXX)"
@@ -193,8 +203,7 @@ function delete_old_dirs()
       then
         log notice "Deleted old data directory: ${dir}"
       else
-        log error "Failed to delete old data directory: ${dir}"
-        exit 1
+        error "Failed to delete old data directory: ${dir}"
       fi
     done
   else
